### ISSUE TITLE
mysql required

### ISSUE THREAD

**Issue by jhriv** [projectblacklight/code4lib_precon_demo#20]
During `bin/setup` an error occurred:

````
checking for mysql_query() in -lmysqlclient... no
-----
mysql client is missing. You may need to 'brew install mysql' or 'port install
mysql', and try again.
-----
*** extconf.rb failed ***
````

[ ] Add MySQL to list of system dependencies

**Comment by cbeer** [comment]
Thanks for the report. I think this is an inadvertent dependency introduced from the demo app we copied from.
