### ISSUE TITLE
Is OpenJDK ok?

### ISSUE THREAD

**Issue by chrissharp123** [projectblacklight/code4lib_precon_demo#9]
I run Fedora 23 and OpenJDK is the preferred Java version.  I see that the setup/bin script expects Oracle Java, but can I just hack the script to be okay with OpenJDK, or is there a reason we need to be using Oracle Java?

Thanks!

Chris

**Comment by chrissharp123** [comment]
I'll add that after hacking the script to allow openjdk, I have solr up and running, so unless there's a reason that's problematic, I think we're good. ;-)

**Comment by cbeer** [comment]
Yes, OpenJDK is just fine. What changes did you need to make to work with it?

**Comment by chrissharp123** [comment]
I changed line 14 to read
`unless `java -version 2&>1` =~ /^(java|openjdk) version "1.[78]/`
which allowed openjdk to work.

**Comment by cbeer** [comment]
Thanks, I've updated the script in this repository.
